name = "Rinthereout"
author = "hub"
version = "0.2.0-indev"
description = "A Kitchen-sink Fabric Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "baf0844721fb8ea59042e603baed14ff4c27eec5e66b327e2175a00bc192f480"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
